services:
  pg_mooncake_dev_service:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY
        - DEV_USERNAME
        - USER_UID
        - USER_GID
    env_file:
      - .env
    container_name: pg_mooncake_dev
    privileged: true
    volumes:
      - ..:/opt/transwarp/pg_mooncake:cached
      - ${LOCAL_CARGO_GIT}:/opt/cargo/git
      - ${LOCAL_CARGO_REGISTRY}:/opt/cargo/registry
      - ${LOCAL_RUSTUP_TOOLCHAINS}:/opt/rustup/toolchains
    working_dir: /opt/transwarp/pg_mooncake
    network_mode: host 
    tty: true
    stdin_open: true
